[2023-02-17 21:51:29,238] [INFO ]- blog: Blog started
[2023-02-17 21:52:26,238] [INFO ]- blog: Blog started
[2023-02-17 21:53:34,623] [INFO ]- blog: Blog started
[2023-02-17 21:55:12,137] [INFO ]- blog: Blog started
[2023-02-17 22:08:30,659] [INFO ]- blog: Blog started
[2023-02-17 22:08:47,438] [INFO ]- blog: Blog started
[2023-02-17 22:09:19,474] [INFO ]- blog: Blog started
[2023-02-17 22:16:58,639] [INFO ]- blog: Blog started
[2023-02-17 22:17:19,958] [INFO ]- blog: Blog started
[2023-02-17 22:17:22,865] [INFO ]- blog: Blog started
[2023-02-17 22:19:37,796] [INFO ]- blog: Blog started
[2023-02-17 22:19:51,376] [INFO ]- blog: Blog started
[2023-02-17 22:32:10,776] [INFO ]- blog: Blog started
[2023-02-17 22:32:43,131] [INFO ]- blog: Blog started
[2023-02-17 22:39:13,074] [INFO ]- blog: Blog started
[2023-02-17 22:39:15,934] [ERROR ]- blog: Exception on / [GET]
Traceback (most recent call last):
  File "Z:\python project\flask_blog\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\python project\flask_blog\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\python project\flask_blog\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\python project\flask_blog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "Z:\python project\flask_blog\views.py", line 8, in index
    return render_template('index.html')
  File "Z:\python project\flask_blog\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "Z:\python project\flask_blog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\python project\flask_blog\templates\index.html", line 1, in template
    {% load static %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.
[2023-02-17 22:40:24,928] [INFO ]- blog: Blog started
[2023-02-17 22:40:25,667] [INFO ]- blog: Blog started
[2023-02-17 23:19:26,672] [INFO ]- blog: Blog started
[2023-02-17 23:25:26,991] [INFO ]- blog: Blog started
[2023-02-17 23:27:07,900] [INFO ]- blog: Blog started
